### ISSUE TITLE
Provide a DefaultChatTheme

### ISSUE THREAD

**Issue by j3k0** [j3k0/starling-chat-console#7]
`ThemeWeb` and `ThemeMobile` don't have to be such repetitions of each other.

Provide a default theme class with sensible defaults, that can be extended. This class can be part of the public API of the module. 

``` actionscript
package fovea.chat.interfaces {
public class DefaultChatTheme implements IChatTheme { ... all defaults functions ... }
}

package fovea.chat.app.test_data {
public class ThemeWeb extends DefaultChatTheme { ... only the specific ... }
}
```

**Comment by JustinWalkerThotkraft** [comment]
My apologies, I should have explained.  Those files are templates for testing.  I didn't intend for those to be used in the final application.  I made them in that fashion so that there would be a clear understanding of the variables defined in each version so when you finalized the art you could define how you wanted the console to appear on both platforms.  Once again I'm sorry for the confusion.

**Comment by JustinWalkerThotkraft** [comment]
Ive made the requested changes and pushed to the repo.  The server now adds a randomized message every 5 seconds.  The chat message now increases in size to accommodate the text in the message.  Ive also updated the console so that when calling the entire chat queue there isnt duplicate data or graphical inconsistencies.  Ive added a loading icon, though I recommend using a bitmap for that icon by going into the file and replacing the code with an AssetManager pull.  Ive also added a failed load icon, I also recommend doing the same for this icon. Ive moved the avatar image down to be centered vertically based on the text as requested.  Lastly, Ive added a border to the reply window.  This border will always be a darker version of the color specified replyWindowBackgroundColor in the theme.
